Repository 3rdflr/part4-team2, pull requests merged in 2025-08, with the labels that each got.

#1 remove unused SVG files and global styles; update layout component
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
Labels: remove 🗑️

#11 feat TRI-5: 공통 버튼, 인풋, 유효성 검사 유틸, axios 인스턴스
  package-lock.json
  public/icon/active_off.svg
  public/icon/active_on.svg
  public/icon/icon_kakao.svg
  src/app/(common)/yeonhui/page.tsx
  src/app/api/axiosInstance.ts
  src/components/common/FormInput.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/lib/utils/validations.ts
Labels: feat ✨, 연희

#13 feat TRI-16: ActivityLIst, Card 추가
  src/app/page.tsx
  src/components/home/ActivityCard.tsx
  src/components/home/ActivityList.tsx
  src/components/home/ActivitySheet.tsx
  src/hooks/useScreenSize.ts
Labels: feat ✨, 창환

#14 feat TRI-18: 로그인/회원가입 기능 구현
  package-lock.json
  public/images/icons/active_off.svg
  public/images/icons/active_on.svg
  public/images/icons/icon_kakao.svg
  public/images/logo_large.svg
  src/app/api/auth.ts
  src/app/api/user.ts
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/common/FormInput.tsx
  src/components/ui/input.tsx
  src/lib/utils/validations.ts
  src/types/auth.type.ts
  src/types/user.type.ts
Labels: feat ✨, 연희

#18 feat TRI-21: 카테고리, 검색창 구현 및 좋아요 기능
  package-lock.json
  package.json
  public/images/icons/Busan.png
  public/images/icons/City_blue.png
  public/images/icons/City_brown.png
  public/images/icons/City_green.png
  public/images/icons/Jeju.png
  public/images/icons/Mountain.png
  public/images/icons/_empty.png
  src/app/page.tsx
  src/components/common/Nav.tsx
  src/components/home/ActivityCard.tsx
  src/components/home/ActivityLike.tsx
  src/components/home/CategoriesData.tsx
  src/components/home/CategoryButton.tsx
  src/components/home/CategoryList.tsx
  src/components/home/Constants.ts
  src/components/home/LoginSection.tsx
  src/components/home/PriceFilter.tsx
  src/components/home/SearchFilters.tsx
  src/components/ui/slider.tsx
  src/hooks/useElemetInView.ts
  src/store/likeStore.ts
  tailwind.config.ts
Labels: feat ✨, 창환, chore ⚙️

#17 fix TRI-19: 이미지 뷰어 및 모달 개선
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  public/images/placeholder.svg
  src/components/common/LoadErrorFallback.tsx
  src/components/pages/activities/ActivityImageViewer.tsx
  src/components/pages/activities/ImageGalleryModal.tsx
  src/hooks/useImageWithFallback.ts
  src/stories/ActivityImageViewer.stories.tsx
  src/stories/ImageGalleryModal.stories.tsx
Labels: feat ✨, 휘건

#19 feat TRI-12: 내 체험 등록/수정 페이지 공통 폼 로직 작성
  build-storybook.log
  package-lock.json
  package.json
  src/app/api/activities.ts
  src/app/my-activities/activity/[activityId]/page.tsx
  src/app/my-activities/activity/page.tsx
  src/components/common/BasicCalendar.tsx
  src/components/common/FormInput.tsx
  src/components/common/reactDayPickerStyle.css
  src/components/pages/myActivities/CategorySelect.tsx
  src/components/pages/myActivities/DateInput.tsx
  src/components/pages/myActivities/DateTimeRow.tsx
  src/components/pages/myActivities/ImageUploader.tsx
  src/components/pages/myActivities/MyActivityForm.tsx
  src/components/pages/myActivities/RoundButton.tsx
  src/components/pages/myActivities/StartEndTimeSelect.tsx
  src/components/ui/button.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/hooks/useDateInput.ts
  src/hooks/useMyActivityForm.tsx
  src/lib/utils/dateUtils.ts
  src/types/daumPostcode.d.ts
  src/types/myActivity.types.ts
  src/types/myActivitySchema.ts
Labels: feat ✨, 수민

#22 refactor TRI-27: 내 체험 등록/수정 페이지 공통 폼 개선사항 반영, 토스트 유틸 추가
  src/components/pages/myActivities/CategorySelect.tsx
  src/components/pages/myActivities/ImageUploadSection.tsx
  src/components/pages/myActivities/ImageUploader.tsx
  src/components/pages/myActivities/MyActivityForm.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/hooks/useMyActivityForm.tsx
  src/lib/utils/myActivitySchema.ts
  src/lib/utils/toastUtils.tsx
Labels: refactor 💡, 수민
