Repository 3rdflr/part4-team2, pull requests merged in 2025-09, with the labels that each got.

#25 feat TRI-28: 내 체험 관리 페이지 내 사이드메뉴 컴포넌트 개발
  src/app/mypage/layout.tsx
  src/app/mypage/my-experience/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/reservation-list/page.tsx
  src/app/mypage/reservation-status/page.tsx
  src/app/mypage/user/page.tsx
  src/components/pages/myActivities/RoundButton.tsx
  src/components/pages/myPage/SideMenu.tsx
  src/components/ui/card.tsx
Labels: feat ✨, 수민

#28 FIX : stroke-width 경고 해결 및 SSG 빌드 오류 수정
  package-lock.json
  src/app/activities/[activityId]/page.tsx
  src/app/api/activities.ts
  src/app/api/axiosInstance.ts
  src/components/home/ActivityCard.tsx
  src/components/home/Constants.tsx
Labels: bug 🐞, fix 🛠️, 휘건

#29 Feat: TRI-26 네이버 지도 기능 추가
  package-lock.json
  package.json
  src/app/activities/[activityId]/ActivityClientPage.tsx
  src/app/api/geocoding.ts
  src/components/common/naverMaps/ImageMarker.tsx
  src/components/common/naverMaps/Marker.tsx
  src/components/common/naverMaps/NaverMap.tsx
  src/components/common/naverMaps/NaverMapCore.tsx
  src/components/common/naverMaps/NaverMapError.tsx
  src/components/common/naverMaps/NaverMapSkeleton.tsx
  src/hooks/useGeocoding.ts
  src/types/geocoding.types.ts
Labels: feat ✨, 휘건

#34 Fix TRI-35: proxy 서버 CORS 요청 처리 개선
  package-lock.json
  src/app/api/proxy/[...path]/route.ts
Labels: bug 🐞, feat ✨, 연희

#33 feat TRI-34: proxy 오류 일부 수정, bottomNav 추가 및 애니메이션 구현,
  next.config.js
  public/images/icons/default_profile_gray.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Nav.tsx
  src/components/home/ActivityCard.tsx
  src/components/home/ActivityLike.tsx
  src/components/home/ActivityList.tsx
  src/components/home/ActivitySheet.tsx
  src/components/home/BottomNav.tsx
  src/components/home/Constants.tsx
  src/components/home/LoginSection.tsx
  src/components/home/NavMobileView.tsx
  src/components/home/PriceFilter.tsx
  src/components/home/SearchFilters.tsx
  src/components/home/SearchResult.tsx
  src/hooks/useInfiniteList.ts
  src/store/likeStore.ts
  src/types/activities.types.ts
Labels: bug 🐞, fix 🛠️, feat ✨, refactor 💡, 창환

#31 Refactor TRI-32: 내 체험 수정 상세 조회 useQuery로 수정
  src/components/pages/myActivities/MyActivityForm.tsx
  src/hooks/useMyActivityForm.tsx
Labels: refactor 💡, 수민

#36 feat TRI-39: 검색시 지도 추가
  src/components/common/Nav.tsx
  src/components/home/ActivityLike.tsx
  src/components/home/ActivitySheet.tsx
  src/components/home/BottomNav.tsx
  src/components/home/MapCard.tsx
  src/components/home/SearchResult.tsx
Labels: feat ✨, 창환

#38 feat TRI-41: footer 추가 / 알림 기능 추가 / wishList 추가 / 네비게이션의 검색창이 랜딩 페이지 외에도 보이는 오류 수정
  src/app/layout.tsx
  src/app/mypage/wishlist/page.tsx
  src/app/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Nav.tsx
  src/components/home/BottomNav.tsx
  src/components/home/LoginSection.tsx
  src/components/home/MapCard.tsx
  src/components/home/NavContent.tsx
  src/components/home/NotificationModal.tsx
  src/components/home/SearchFilters.tsx
  src/hooks/useNotification.ts
Labels: feat ✨, 창환

#39 fix TRI-43: route params, multipart/form-data 수정
  src/app/api/proxy/[...path]/route.ts
Labels: fix 🛠️, 수민

#40 feat TRI-36: 카카오 회원가입/로그인 기능 추가 및 기존 alert -> 토스트 알람으로 변경
  src/app/api/axiosInstance.ts
  src/app/api/oauth.ts
  src/app/login/callback/page.tsx
  src/app/login/page.tsx
  src/app/signup/callback/page.tsx
  src/app/signup/page.tsx
  src/lib/utils/randomNicknameUtils.ts
  src/types/oauth.type.ts
Labels: feat ✨, 연희

#43 fix TRI-45: 검색창 애니메이션 개선 등
  src/components/common/Nav.tsx
  src/components/home/ActivityCard.tsx
  src/components/home/ActivitySheet.tsx
  src/components/home/BottomNav.tsx
  src/components/home/LoginSection.tsx
  src/components/home/NavMobileView.tsx
  src/components/home/SearchFilters.tsx
  src/components/home/SearchResult.tsx
Labels: fix 🛠️, 창환

#45 fix TRI-38: 토큰 발급 및 이슈 해결 / 중간 점검 피드백 반영
  src/app/api/axiosInstance.ts
  src/app/api/logout/route.ts
  src/app/api/proxy/[...path]/route.ts
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/ui/input.tsx
  src/hooks/useAuthRedirect.ts
  src/lib/utils/logoutUtils.ts
  src/lib/utils/validations.ts
Labels: fix 🛠️, 연희

#44 feat TRI-46: 인기순 리스트 개발
  public/images/icons/Logo_bottom.svg
  public/images/icons/Logo_top.svg
  src/app/globals.css
  src/app/page.tsx
  src/components/common/Footer.tsx
  src/components/home/ActivityCard.tsx
  src/components/home/ActivityList.tsx
  src/components/home/BestActityList.tsx
  src/components/home/Constants.tsx
  src/components/home/NavMobileView.tsx
  src/components/home/SearchFilters.tsx
Labels: fix 🛠️, feat ✨, 창환

#48 Feat TRI-42 예약 페이지 리팩토링 및 레이아웃 개선
  package-lock.json
  package.json
  src/app/activities/[activityId]/ActivityClientPage.tsx
  src/app/activities/[activityId]/page.tsx
  src/app/activities/[activityId]/queryClients.ts
  src/app/api/activities.ts
  src/app/globals.css
  src/components/common/BasicCalendar.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/InfinityScroll.tsx
  src/components/pages/activities/ActivityInfo.tsx
  src/components/pages/activities/ImageGalleryModal.tsx
  src/components/pages/activities/ReviewList.tsx
  src/components/pages/activities/bookingCard/BookingCalendar.tsx
  src/components/pages/activities/bookingCard/BookingCard.tsx
  src/components/pages/activities/bookingCard/BookingCardDesktop.tsx
  src/components/pages/activities/bookingCard/BookingCardMobile.tsx
  src/components/pages/activities/bookingCard/BookingConfirm.Modal.tsx
  src/components/pages/activities/bookingCard/BookingContainer.tsx
  src/components/pages/activities/bookingCard/BookingDetail.tsx
  src/components/pages/activities/bookingCard/BookingMember.tsx
  src/components/pages/activities/bookingCard/BookingTimeList.tsx
  src/components/pages/activities/bookingCard/BookingTimeSlot.tsx
  src/components/ui/dropdown-menu.tsx
  src/hooks/useMyActivityForm.tsx
  src/hooks/useScheduleGrouping.ts
  src/hooks/useSchedulesByDate.ts
  src/lib/utils/schedule.utils.ts
  src/mocks/schedules.mock.ts
  src/types/activities.type.ts
Labels: feat ✨, refactor 💡, 휘건

#50 fix TRI-54: Warning 수정
  src/app/activities/[activityId]/ActivityClientPage.tsx
  src/components/common/Footer.tsx
  src/components/common/Nav.tsx
  src/components/home/ActivityCard.tsx
  src/components/home/ActivityList.tsx
  src/components/home/BestActityList.tsx
  src/components/home/BestActivityClient.tsx
  src/components/home/BottomNav.tsx
  src/components/home/LoginSection.tsx
  src/components/home/NavMobileView.tsx
  src/components/home/NotificationModal.tsx
  src/components/home/RecentView.tsx
  src/components/home/SearchFilters.tsx
  src/components/home/SearchResult.tsx
  src/hooks/useNotification.ts
  src/hooks/useScreenSize.ts
Labels: fix 🛠️, feat ✨, 창환

#51 refactor TRI-48: 로그인/회원가입 리펙토링, 카카오 회원이 아닐 경우 관련 안내 모달 추가
  src/app/(common)/yeonhui/page.tsx
  src/app/api/axiosInstance.ts
  src/app/login/callback/page.tsx
  src/app/login/page.tsx
  src/app/signup/callback/page.tsx
  src/app/signup/page.tsx
  src/components/common/ConfirmActionModal.tsx
  src/components/pages/auth/AuthFormValidations.tsx
  src/components/pages/auth/AuthHelperText.tsx
  src/components/pages/auth/Divider.tsx
  src/components/pages/auth/KakaoButton.tsx
  src/components/pages/auth/LogoImage.tsx
  src/components/pages/auth/kakao.ts
  src/lib/utils/randomNicknameUtils.ts
  src/lib/utils/validations.ts
Labels: feat ✨, 연희, refactor 💡

#55 Fix TRI-69 마이페이지 페이지들 계정 변경 시 api 다시 안불러오는 오류 수정
  src/app/mypage/my-experience/page.tsx
  src/app/mypage/reservation-list/page.tsx
  src/app/mypage/reservation-status/page.tsx
  src/app/mypage/user/page.tsx
Labels: fix 🛠️, 수민

#57 Fix TRI-70 체험 관리 페이지 내 체험 삭제 시 오류 및 반응형 수정
  src/app/api/proxy/[...path]/route.ts
  src/app/mypage/layout.tsx
  src/app/mypage/my-experience/page.tsx
  src/components/pages/myPage/MyExperienceCard.tsx
Labels: bug 🐞, fix 🛠️, 수민
